export const apiUrl = document.location.href.startsWith("http://localhost")
  ? "http://localhost:5000"
  : "";

export const endPoint = {
  HOME: "/",
  DASHBOARD: "/dashboard",
};

export const modalMessage = {
  LOADING: 'Please wait ...',
  APP_NAME: 'Bled Store',
  PASSWORD_AMD_CONFIRM:
    "Password and Confirmation Password are differents. Try again.",
  ORDER_NOT_FOUND: "Orders not found.",
  ORDERS_HISTORY: "Orders History",
  GO_SHOPPING: "Go Shopping",
  SIGN_IN: "Sign In",
  SIGN_UP: "Sign Up",
  SIGN_OUT: "Sign Out",
  PSEUDO: 'Pseudo',
  PLACEHOLDER_PSEUDO: 'Enter your pseudo name',
  EMAIL: "Email Address",
  PLACEHOLDER_EMAIL: 'Enter your address email',
  PASSWORD: "Password",
  CONFIRM_PASSWORD: "Confirmation Password",
  PLACEHOLDER_PASSWORD: "Enter your password",
  PLACEHOLDER_CONFIRM_PASSWORD: "Confirm your password",
  GENDER: 'Sex',
  GENDER_MALE: 'Male',
  GENDER_FEMALE: 'Female',
  PHONE: 'Phone Number',
  PLACEHOLDER_PHONE: "Enter your phone number",
  SIGN_IN_BUTTON: "Enter",
  NEW_USER: "New User?",
  CREATE_ACCOUNT: "Create a new account",
  REGISTER: "Register",
  LOGIN: "Login",
  ACCOUNT_ALREADY: "Already have an account?",
  FULLNAME: "Full Name",
  PLACEHOLDER_FULLNAME: "Enter your fullname",
  PRODUCTS: "Store Products",
  BACK_DASHBOARD_PRODUCTS: "Back to Products List",
  CREATE_PRODUCT: "Create Product",
  ID_PRODUCT: "ID Product",
  NAME_PRODUCT: "Name",
  COUNT_IN_STOCK: "Count In Stock",
  CATEGORY: "Category",
  BRAND: "Brand",
  IMAGE: "Image",
  DESCRIPTION: "Description",
  PRICE: "Price",
  ACTIONS: "Actions",
  CREATE: "Create",
  UPDATE: "Update",
  UPDATE_PROFILE: "Update Profile",
  EDIT: "Edit",
  DELETE: "Delete",
  CURRENCY: "€",
  ID_ORDER: "ID Product",
  DATE: "Date",
  TOTAl: "Total",
  USER: "User",
  USER_PROFILE: "User Profile",
  PAID_AT: "Paid At",
  DELIVERED_AT: "Delivered At",
  NO: "No",
  FORMAT_FULL_DATE: "DD/MM/YYYY HH:mm:ss",
  FORMAT_DATE: "DD/MM/YYYY",
  PAID: "Paid",
  MEMBER_SINCE: 'Member since'
};
